# Amazon Bedrock AgentCore Configuration
# MBTI Travel Assistant MCP Server

name: "mbti-travel-assistant-mcp"
description: "MBTI Travel Assistant that orchestrates MCP client calls to restaurant search and reasoning services"
version: "1.0.0"

# Platform Configuration - ARM64 required for AgentCore Runtime
platform: "linux/arm64"
container_runtime: "docker"

# Network Configuration
network_mode: "PUBLIC"

# Runtime Configuration
runtime:
  type: "agentcore"
  framework: "strands-agents"
  
# Authentication Configuration
authentication:
  type: "jwt"
  config:
    customJWTAuthorizer:
      allowedClients: []  # To be configured during deployment
      discoveryUrl: ""    # To be configured with Cognito User Pool

# Observability Configuration
observability:
  enabled: true
  tracing: true
  metrics: true
  logs: true
  
# Environment Variables
environment:
  AWS_REGION: "us-east-1"
  AWS_DEFAULT_REGION: "us-east-1"
  DOCKER_CONTAINER: "1"
  LOG_LEVEL: "INFO"
  
# Resource Configuration
resources:
  cpu: "1 vCPU"
  memory: "2 GB"
  
# Scaling Configuration
scaling:
  min_instances: 1
  max_instances: 10
  target_utilization: 70

# Health Check Configuration
health_check:
  path: "/health"
  interval: 30
  timeout: 5
  retries: 3