global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@mbti-travel-assistant.com'
  smtp_auth_username: 'alerts@mbti-travel-assistant.com'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h
    - match:
        service: authentication
      receiver: 'security-alerts'
      group_wait: 5s
      repeat_interval: 15m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'ops-team@mbti-travel-assistant.com'
        subject: '[CRITICAL] MBTI Travel Assistant Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          Dashboard: http://grafana.mbti-travel-assistant.com/d/mbti-overview
        headers:
          Priority: 'high'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#ops-critical'
        title: 'CRITICAL: MBTI Travel Assistant Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .GroupLabels.service }}
          *Severity:* {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'dev-team@mbti-travel-assistant.com'
        subject: '[WARNING] MBTI Travel Assistant Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          Dashboard: http://grafana.mbti-travel-assistant.com/d/mbti-overview
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#ops-warnings'
        title: 'WARNING: MBTI Travel Assistant Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true

  - name: 'security-alerts'
    email_configs:
      - to: 'security-team@mbti-travel-assistant.com'
        subject: '[SECURITY] MBTI Travel Assistant Security Alert'
        body: |
          SECURITY ALERT
          
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          Please investigate immediately.
        headers:
          Priority: 'high'
          X-Security-Alert: 'true'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#security-alerts'
        title: '🚨 SECURITY ALERT: MBTI Travel Assistant'
        text: |
          *SECURITY ALERT*
          
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
          
          Please investigate immediately.
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

templates:
  - '/etc/alertmanager/templates/*.tmpl'