global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'mbti-travel-assistant-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # MBTI Travel Assistant MCP Service - Production
  - job_name: 'mbti-travel-assistant-prod'
    static_configs:
      - targets: ['mbti-travel-assistant:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true
    params:
      format: ['prometheus']

  # AgentCore Runtime Metrics - Production
  - job_name: 'agentcore-runtime-prod'
    static_configs:
      - targets: ['mbti-travel-assistant:8080']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Nginx Reverse Proxy Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # External MCP Servers Health Checks
  - job_name: 'external-mcp-health'
    static_configs:
      - targets: 
        - 'prod-search-mcp.agentcore.aws'
        - 'prod-reasoning-mcp.agentcore.aws'
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 30s
    scheme: https

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 60s

  # Fluentd Metrics
  - job_name: 'fluentd'
    static_configs:
      - targets: ['fluentd:24231']
    metrics_path: '/metrics'
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# Production storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true