version: '3.8'

services:
  # Development server
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080
    command: npm run dev
    profiles:
      - dev

  # Production build
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    profiles:
      - prod

  # Staging build
  staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: staging
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    profiles:
      - staging