AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Insurance API Lambda with API Gateway

Parameters:
  EnvironmentType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  
Resources:
  InsuranceApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub insurance-api-${EnvironmentType}
      CodeUri: .
      Handler: lambda_function.handler
      Runtime: python3.10
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentType
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref InsuranceApiGateway
      Policies:
        - AWSLambdaBasicExecutionRole

  InsuranceApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub insurance-api-gateway-${EnvironmentType}
      StageName: !Ref EnvironmentType
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  InsuranceApiFunction:
    Description: Insurance API Lambda Function ARN
    Value: !GetAtt InsuranceApiFunction.Arn
  
  InsuranceApiGateway:
    Description: API Gateway endpoint URL
    Value: !Sub https://${InsuranceApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentType}/
    
  InsuranceApiGatewayConsole:
    Description: API Gateway console URL
    Value: !Sub https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/apis/${InsuranceApiGateway}/resources