---
# User Preferences Configuration
# This file defines user preferences that can be loaded into the SRE agent memory system

users:
  Alice:
    preferences:
      - preference_type: "escalation"
        preference_value:
          primary_contact: "alice.manager@company.com"
          secondary_contact: "sre-oncall@company.com"
          escalation_threshold: "high"
          escalation_delay_minutes: 15
        context: "User preference configuration from user_config.yaml"
      
      - preference_type: "notification"
        preference_value:
          channels: ["#alice-alerts", "#sre-team"]
          quiet_hours:
            start: "22:00"
            end: "08:00"
          severity_filter: "medium"
        context: "User preference configuration from user_config.yaml"
      
      - preference_type: "workflow"
        preference_value:
          investigation_style: "detailed"
          auto_approve_simple_plans: true
          preferred_agents: ["kubernetes", "logs", "runbooks", "metrics"]
          max_investigation_time_minutes: 30
        context: "User preference configuration from user_config.yaml"
      
      - preference_type: "style"
        preference_value:
          communication_style: "technical"
          report_format: "executive_summary"
          include_troubleshooting_steps: true
          preferred_timezone: "UTC"
        context: "User preference configuration from user_config.yaml"

  Carol:
    preferences:
      - preference_type: "escalation"
        preference_value:
          primary_contact: "carol.director@company.com"
          secondary_contact: "executive-team@company.com"
          escalation_threshold: "medium"
          escalation_delay_minutes: 20
        context: "User preference configuration from user_config.yaml"
      
      - preference_type: "notification"
        preference_value:
          channels: ["#carol-executive", "#strategic-alerts"]
          quiet_hours:
            start: "21:00"
            end: "09:00"
          severity_filter: "critical"
          include_metrics: false
          executive_summary_only: true
        context: "User preference configuration from user_config.yaml"
      
      - preference_type: "workflow"
        preference_value:
          investigation_style: "executive"
          auto_approve_simple_plans: true
          preferred_agents: ["kubernetes", "logs", "runbooks", "metrics"]
          max_investigation_time_minutes: 15
          require_business_impact_analysis: true
        context: "User preference configuration from user_config.yaml"
      
      - preference_type: "style"
        preference_value:
          communication_style: "executive"
          report_format: "executive_summary"
          include_troubleshooting_steps: false
          preferred_timezone: "EST"
          focus_on_business_impact: true
          brief_updates_only: true
        context: "User preference configuration from user_config.yaml"

# Configuration metadata
config:
  version: "1.0"
  description: "User preferences for SRE agent system"
  last_updated: "2025-07-29"